### ISSUE TITLE
Потеря прав после перезахода в игру. | Loss of perms after rejoining

### ISSUE THREAD

**Issue by j0sky** [NukkitRu/Multipass#1]
Захожу на сервер первый раз - права есть. 
Выхожу из игры, захожу снова - прав нет.
Хранится все в yaml. 
auto-update-interval: 10s - не помогает.
Та же проблема и у других игроков сервера.
В логах это:

```
04:24:35 [INFO] [Игрок] _x0 вышел из игры
04:24:35 [INFO] _x0[/94.152.81.127:19132] отключился: client disconnect
04:24:44 [INFO] [AnyVersion] _x0 is using correct protocol version
04:24:44 [INFO] [Multipass] Loading permissions _x0
04:24:44 [INFO] [Multipass] Recalculate permissions: _x0
04:24:44 [INFO] _x0[/94.152.81.127:19132] вошел с id сущности 50 на (world, 227.0, 74.0, 158.0)
```
# 

I went to the server for the first time - right there.
I came out of the game, I go back - no rights.
Keep all in yaml.
auto-update-interval: 10s - does not help.

**Comment by fromgate** [comment]
If player has only default permissions (member only of default group) player data will not saved.
Files will be created only if you add player to another groups or add him additional permissions.

--------------------------

Если у игрока только дефолтные пермишены (т.е. он находится в дефолтной группе), то файл игрока не сохраняется. Он должен создаваться только если игрока добавить в какие-то другие группы или назначить ему дополнительные пермишены.
