### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by bonnedav** [NukkitRu/Multipass#4]
When I try to compile I get this: http://pastebin.com/vyLZe4W5

**Comment by fromgate** [comment]
\Users\David\build\Multipass\src\main\java\ru\nukkit\multipass\data\yaml\YamlSource.java:[118,47] error: unmappable character for encoding Cp1252

If you using Windows you must enable UTF-8 in console using command
chcp 65001

**Comment by bonnedav** [comment]
It is not working.

**Comment by bonnedav** [comment]
http://pastebin.com/iYmB3Cra

**Comment by bonnedav** [comment]
Please help me. It won't compile on GNU/Linux ether.

**Comment by asyven** [comment]
can't compile too, help please
